default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: movies_development
  username: labber
  password: labber

  host: localhost

  port: 5432

test:
  <<: *default
  database: movies_test
  username: labber
  password: labber

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
