default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: movies_development
  username: development
  password: development

  host: localhost

  port: 5432

test:
  <<: *default
  database: movies_test
  username: development
  password: development

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
